server:
  port: 8888

spring:
  application:
    name: Configuration
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Desktop/projects/microservices/configurations/src/main/resources